apps/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    # Existing URL patterns
    path('select_master/', views.select_master, name='select_master'),
    path('select_service/<int:master_id>/', views.select_service, name='select_service'),
    path('select_date/<int:service_id>/<int:master_id>/', views.select_date, name='select_date'),
    path('select_time/<int:service_id>/<int:master_id>/<str:selected_date>/', views.select_time, name='select_time'),
    # New URL pattern for booking the appointment
    path('book_appointment/<int:service_id>/<int:master_id>/<str:selected_date>/<str:selected_time>/', views.book_appointment, name='book_appointment'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('masters/', include('apps.masters.urls')),
    path('appointments/', include('apps.appointments.urls', namespace='appointments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/appointments/models.py
# apps/appointments/models.py
from django.db import models
from apps.clients.models import Client
from apps.masters.models import Master
from apps.services.models import Service

class Appointment(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    master = models.ForeignKey(Master, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    date = models.DateTimeField(null=True, blank=True, default=None)
    description = models.TextField(blank=True, null=True)
    status = models.CharField(max_length=20, default='scheduled')

    def __str__(self):
        return f'Мастер: {self.master} - Услуга: {self.service} - Клиент: {self.client}'

    

class ConfirmationCode(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    code = models.CharField(max_length=10)
    expiration = models.DateTimeField()

    def __str__(self):
        return self.code

apps/appointments/forms.py
from django import forms
from apps.services.models import Service
from apps.masters.models import Master
from apps.clients.models import Client


class ServiceForm(forms.Form):
    service = forms.ModelChoiceField(queryset=Service.objects.all(), label='Выберите услугу')


class MasterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        selected_service = kwargs.pop('selected_service', None)
        super(MasterForm, self).__init__(*args, **kwargs)
        if selected_service:
            self.fields['master'].queryset = Master.objects.filter(service=selected_service)

    master = forms.ModelChoiceField(queryset=Master.objects.all(), label='Выберите мастера', widget=forms.RadioSelect)


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'phone_number']

apps/appointments/views.py
from datetime import timedelta, datetime, time
import datetime
from django.utils import timezone
from django.shortcuts import render, redirect

from apps.appointments.forms import ClientForm, MasterForm, ServiceForm
from apps.appointments.models import Appointment
from apps.masters.models import Master
from apps.services.models import Service


def select_master(request):
    if request.method == 'POST':
        form = MasterForm(request.POST)
        if form.is_valid():
            master_id = form.cleaned_data['master'].id
            return redirect('appointments:select_service', master_id=master_id)
    else:
        form = MasterForm()
    return render(request, 'appointments/select_master.html', {'master_form': form})


def select_service(request, master_id):
    selected_master = Master.objects.get(pk=master_id)

    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            service_id = form.cleaned_data['service'].id
            return redirect('appointments:select_date', service_id=service_id, master_id=master_id)
    else:
        # Фильтруем услуги на основе выбранного мастера
        available_services = Service.objects.filter(master=selected_master)
        form = ServiceForm()

    # Обновляем форму, чтобы она отображала только доступные услуги для выбранного мастера
    form.fields['service'].queryset = available_services

    return render(request, 'appointments/select_service.html', {
        'service_form': form,
        'selected_master': selected_master,
    })


def select_date(request, service_id, master_id):
    selected_service = Service.objects.get(pk=service_id)
    selected_master = Master.objects.get(pk=master_id)

    # Fetch the master's schedule, if it exists
    master_schedule = selected_master.schedule

    # Calculate the next 7 days starting from today
    today = timezone.now().date()
    next_seven_days = [today + timedelta(days=i) for i in range(7)]

    # Get the working days for the master
    working_days = []
    if master_schedule:
        working_days = master_schedule.working_days.all()

    # Filter the next 7 days to include only working days
    available_days = [day for day in next_seven_days if day.weekday() + 1 in [working_day.day_of_week for working_day in working_days]]

    return render(request, 'appointments/select_date.html', {
        'selected_service': selected_service,
        'selected_master': selected_master,
        'available_days': available_days
    })
    
    
def select_time(request, service_id, master_id, selected_date):
    selected_service = Service.objects.get(pk=service_id)
    selected_master = Master.objects.get(pk=master_id)

    # Получаем выбранную дату из URL и преобразуем ее в объект типа datetime.date
    selected_date = timezone.datetime.strptime(selected_date, "%Y-%m-%d").date()

    # Получаем график работы мастера
    master_schedule = selected_master.schedule

    # Получаем рабочий день для выбранной даты
    working_day = master_schedule.working_days.filter(day_of_week=selected_date.weekday() + 1).first()

    # Если для выбранной даты нет рабочего дня, возвращаем сообщение об ошибке или перенаправляем на страницу ошибки
    if not working_day:
        return render(request, 'appointments/no_working_day.html', {
            'selected_service': selected_service,
            'selected_master': selected_master,
            'selected_date': selected_date
        })

    # Рассчитываем начальное и конечное время для выбранной даты
    start_time = timezone.datetime.combine(selected_date, working_day.start_time)
    end_time = timezone.datetime.combine(selected_date, working_day.end_time)

    # Рассчитываем продолжительность выбранной услуги
    service_duration = selected_service.duration

    # Рассчитываем доступные временные интервалы для выбранной даты (хранить в виде объектов типа datetime.time)
    available_time_slots = []
    while start_time + timedelta(minutes=service_duration) <= end_time:
        available_time_slots.append(start_time.time())
        start_time += timedelta(minutes=service_duration)

    if request.method == 'POST':
        # Обрабатываем отправку формы для выбора времени
        # Проверяем, что поле 'selected_time' присутствует в POST-запросе
        if 'selected_time' in request.POST:
            selected_time = request.POST['selected_time']
        else:
            selected_time = None  # или установите значение по умолчанию, например, selected_time = ""

        return redirect('appointments:book_appointment', service_id=service_id, master_id=master_id, selected_date=selected_date, selected_time=selected_time)

    return render(request, 'appointments/select_time.html', {
        'selected_service': selected_service,
        'selected_master': selected_master,
        'selected_date': selected_date,
        'available_time_slots': available_time_slots
    })
    
    
def book_appointment(request, service_id, master_id, selected_date, selected_time):
    selected_service = Service.objects.get(pk=service_id)
    selected_master = Master.objects.get(pk=master_id)

    # Парсим selected_date из строки URL и преобразуем его в объект datetime.date
    selected_date = datetime.datetime.strptime(selected_date, "%Y-%m-%d").date()

    # Если selected_time равен строке 'None' (например, при GET запросе), устанавливаем его равным None
    if selected_time == 'None':
        selected_time = None
    else:
        # Если selected_time не пустой строкой, конвертируем его в объект datetime.time
        selected_time = datetime.datetime.strptime(selected_time, "%H:%M").time()

    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            # Save the client information to the database
            client = form.save()

            # Combine date and time into a single datetime value if selected_time is not None
            appointment_datetime = datetime.combine(selected_date, selected_time) if selected_time is not None else None

            # Save the appointment to the database
            appointment = Appointment.objects.create(
                client=client,
                service=selected_service,
                master=selected_master,
                date=appointment_datetime
            )

            # Perform any other actions related to the appointment (e.g., sending confirmation emails)

            return render(request, 'appointments/appointment_success.html', {
                'appointment': appointment,
                'selected_service': selected_service,
                'selected_master': selected_master,
                'selected_date': selected_date,
                'selected_time': selected_time,
            })
    else:
        form = ClientForm()

    return render(request, 'appointments/book_appointment.html', {
        'client_form': form,
        'selected_service': selected_service,
        'selected_master': selected_master,
        'selected_date': selected_date,
        'selected_time': selected_time,
    })

apps/appointments/templates/appointments/appointment_success.html
{% extends 'base.html' %}
{% block content %}
<div class="container-full-height">
    <h1>Appointment Successfully Booked</h1>
    <p>Client: {{ appointment.client }}</p>
    <p>Service: {{ selected_service }}</p>
    <p>Master: {{ selected_master }}</p>
    <p>Date: {{ selected_date }}</p>
    <p>Time: {{ selected_time }}</p>
</div>
{% endblock %}

apps/appointments/templates/appointments/book_appointment.html
{% extends 'base.html' %}
{% block content %}
<div class="container-full-height">
  <form method="post">
      {% csrf_token %}
      {{ client_form.as_p }}
      <button type="submit">Book Appointment</button>
  </form>
</div>
{% endblock %}

apps/appointments/templates/appointments/select_date.html
{% extends 'base.html' %}
{% block content %}
<div class="container-full-height">
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1>Выберите дату</h1>
                <p>Услуга: {{ selected_service.name }}</p>
                <p>Специалист: {{ selected_master.user.first_name }}</p>
                <ul class="list-group">
                    {% for date in available_days %}
                        <li class="list-group-item">
                            <a href="{% url 'appointments:select_time' selected_service.id selected_master.id date %}">
                                {{ date }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/appointments/templates/appointments/select_master.html
{% extends 'base.html' %}
{% block content %}
<style>
  .card.checked {
    border: 2px solid blue;
  }
</style>
<div class="container-full-height">
    <h1 class="text-center">Выберите специалиста</h1>
    <form method="post" class="text-center">
        {% csrf_token %}
        {% for master in master_form.master.field.queryset %}
        <label class="card my-3" style="width: 200px; display: inline-block; cursor: pointer;">
            <div class="card-body">
                <img src="{{ master.photo.url }}" alt="{{ master.name }}" class="card-img-top rounded-circle" style="width: 100px; height: 100px; object-fit: cover;">
                <p class="card-text">{{ master.user.first_name }}</p>
            </div>
            <input type="radio" name="{{ master_form.master.name }}" value="{{ master.pk }}" style="display: none;">
        </label>
        {% endfor %}
        <div class="text-center"> <!-- Обертка для кнопки -->
            <button type="submit" class="btn btn-primary">Далее</button>
        </div>
    </form>
</div>
<script>
  const cards = document.querySelectorAll('.card');
  cards.forEach(card => {
    card.addEventListener('click', () => {
      cards.forEach(c => c.classList.remove('checked'));
      card.classList.add('checked');
    });
  });
</script>
{% endblock %}

apps/appointments/templates/appointments/select_service.html
{% extends 'base.html' %}
{% block content %}
<style>
    .service-container {
        position: relative;
        border: 1px solid #ccc;
        padding: 10px;
        margin-bottom: 10px;
        cursor: pointer;
    }

    .service-container:hover {
        border-color: #999;
    }

    .service-container input[type="radio"] {
        display: none;
    }

    /* Применяем стили к выбранному контейнеру */
    .service-container input[type="radio"]:checked + span {
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        outline: 2px solid #007bff;
    }
</style>
<div class="container-full-height">
    <h1>Выберите услугу специалиста {{ selected_master.user.first_name }}</h1>
    <form method="post">
        {% csrf_token %}
        {% for service in service_form.service.field.queryset %}
            <label class="service-container">
                <input type="radio" name="service" value="{{ service.pk }}">
                {{ service }} <span></span>
            </label>
        {% endfor %}
        <input type="hidden" id="selected_service" name="service">
        <input type="submit" value="Next">
    </form>
</div>
<script>
    const serviceContainers = document.querySelectorAll('.service-container');

    serviceContainers.forEach(container => {
        container.addEventListener('click', () => {
            const input = container.querySelector('input[type="radio"]');
            document.getElementById("selected_service").value = input.value;

            // Remove checked class from all containers
            serviceContainers.forEach(c => {
                c.classList.remove('checked');
            });

            // Add checked class to the clicked container
            container.classList.add('checked');
        });
    });
</script>
{% endblock %}

apps/appointments/templates/appointments/select_time.html
{% extends 'base.html' %}

{% block content %}
<style>
    .time-slot-container {
        position: relative;
        border: 1px solid #ccc;
        padding: 10px;
        margin-bottom: 10px;
        cursor: pointer;
    }

    .time-slot-container:hover {
        border-color: #999;
    }

    /* Применяем стили к выбранному контейнеру */
    .time-slot-container.checked {
        outline: 2px solid #007bff;
    }
</style>
<div class="container-full-height">
    <h1>Выберите время</h1>
    <p>Service: {{ selected_service.name }}</p>
    <p>Master: {{ selected_master.user.first_name }}</p>
    <p>Date: {{ selected_date }}</p>
    <form method="POST">
        {% csrf_token %}
        {% for time_slot in available_time_slots %}
            <label class="time-slot-container" onclick="selectTime('{{ time_slot|time:"H:i" }}')">
                <input type="radio" name="time_slot" value="{{ time_slot|time:"H:i" }}" style="display: none;">
                {{ time_slot|time:"H:i" }}
            </label>
        {% endfor %}
        <input type="hidden" id="selected_time" name="time_slot">
        <input type="submit" value="Book Appointment">
    </form>
</div>
<script>
    function selectTime(time) {
        const containers = document.querySelectorAll('.time-slot-container');
        containers.forEach(container => {
            container.classList.remove('checked');
        });
        const selectedContainer = document.querySelector(`.time-slot-container input[value="${time}"]`);
        if (selectedContainer) {
            selectedContainer.parentNode.classList.add('checked');
            document.getElementById("selected_time").value = time;
        }
    }
</script>
{% endblock %}