apps/appointments/urls.py
from django.urls import path
from . import views

app_name = 'appointments'

urlpatterns = [
    # Existing URL patterns
    path('select_master/', views.select_master, name='select_master'),
    path('select_service/<int:master_id>/', views.select_service, name='select_service'),
    path('select_date/<int:service_id>/<int:master_id>/', views.select_date, name='select_date'),
    path('select_time/<int:service_id>/<int:master_id>/<str:selected_date>/', views.select_time, name='select_time'),
    # New URL pattern for booking the appointment
    path('book_appointment/<int:service_id>/<int:master_id>/<str:selected_date>/<str:selected_time>/', views.book_appointment, name='book_appointment'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
    path('masters/', include('apps.masters.urls')),
    path('appointments/', include('apps.appointments.urls', namespace='appointments')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
{% block content %}
    <footer class="bg-black text-center py-5">
        <div class="container px-5">
            <div class="text-white-50 small">
                <div class="mb-2">Следите за нами в социальных сетях</div>
                <a href="https://www.instagram.com/nails_health_/"><i class="bi bi-instagram"></i></a>
                <span class="mx-1">&middot;</span>
                <a href="https://wa.me/996755470074"><i class="bi bi-whatsapp"></i></a>
                <span class="mx-1">&middot;</span>
                <a href="tel:0755470074"><i class="bi bi-telephone"></i></a>
            </div>
        </div>
    </footer>
{% endblock %}

templates/includes/navbar.html
{% load static %}
{% block content %}
    <nav class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm" id="mainNav">
        <div class="container px-5">
            <a class="navbar-brand fw-bold" href="{% url 'index' %}">
                <img src="{% static 'assets/img/logo.png' %}" alt="Start Bootstrap Логотип" style="max-width: 150px; max-height: 150px;">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" style="border: none; text-decoration: none; color: black;">
                <img src="./assets/img/menu.png" alt="Start Bootstrap Логотип" style="max-width: 30px; max-height: 30px;">
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
                    <li class="nav-item"><a class="nav-link me-lg-3" href="#features">Услуги</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="#download">Наши мастера</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="#download">Адрес</a></li>
                    <li class="nav-item"><a class="nav-link me-lg-3" href="#download">Сотрудникам</a></li>
                </ul>
                <a class="custom-btn" href="{% url 'appointments:select_master' %}">Записаться</a>
            </div>
        </div>
    </nav>
{% endblock %}